services:
  geoip-api:
    build: .
    image: ytzcom/geoip-api:latest
    container_name: geoip-api
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      # API Configuration
      - API_KEYS=${API_KEYS}
      
      # Storage Configuration
      - STORAGE_MODE=${STORAGE_MODE:-s3}
      
      # S3 Configuration (for s3/hybrid modes)
      - S3_BUCKET=${S3_BUCKET:-ytz-geoip}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - URL_EXPIRY_SECONDS=${URL_EXPIRY_SECONDS:-3600}
      
      # Local Storage (for local/hybrid modes)
      - LOCAL_DATA_PATH=/data
      
      # Server Configuration
      - WORKERS=${WORKERS:-1}
      - DEBUG=${DEBUG:-false}
      
      # Admin Configuration
      - ENABLE_ADMIN=${ENABLE_ADMIN:-false}
      - ADMIN_KEY=${ADMIN_KEY}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    
    volumes:
      # Mount local data directory for local/hybrid storage modes
      - ${LOCAL_DATA_PATH:-./data}:/data:ro
    
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"