apiVersion: v1
kind: ConfigMap
metadata:
  name: geoip-config
  namespace: geoip-system
  labels:
    app.kubernetes.io/name: geoip-updater
    app.kubernetes.io/component: config
data:
  # Update configuration
  target-dir: "/data"
  log-file: "/logs/geoip-update.log"
  max-retries: "3"
  timeout: "300"
  max-concurrent: "4"
  
  # Databases to download (comma-separated or "all")
  databases: "all"
  
  # Python config.yaml (optional, for Python implementation)
  config.yaml: |
    target_dir: "/data"
    databases:
      - "all"
    max_retries: 3
    timeout: 300
    max_concurrent: 4
    verify_ssl: true
    user_agent: "GeoIP-Update-K8s/1.0"