apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: geoip-system

resources:
  - namespace.yaml
  - priorityclass.yaml
  - rbac.yaml
  - pvc.yaml
  - secret.yaml
  - configmap.yaml
  - networkpolicy.yaml
  - cronjob-secure.yaml

images:
  - name: your-registry/geoip-updater
    newTag: latest

configMapGenerator:
  - name: geoip-config
    literals:
      - target-dir=/data
      - log-file=/logs/geoip-update.log
      - databases=GeoLite2-ASN.mmdb,GeoLite2-City.mmdb,GeoLite2-Country.mmdb,IP2LOCATION-LITE-DB1.BIN,IP2LOCATION-LITE-DB3.BIN,IP2LOCATION-LITE-DB5.BIN,IP2LOCATION-LITE-DB9.BIN,IP2LOCATION-LITE-DB11.BIN

secretGenerator:
  - name: geoip-api-credentials
    literals:
      - api-key=your-api-key-here
      - api-endpoint=https://your-api.execute-api.region.amazonaws.com/v1/auth

patchesStrategicMerge:
  - |-
    apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: geoip-updater
      namespace: geoip-system
    spec:
      schedule: "0 2 * * *"  # Override schedule if needed

labels:
  - pairs:
      environment: production
      managed-by: kustomize
    includeSelectors: true
    includeTemplates: true

replicas:
  - name: geoip-updater
    count: 1